[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/napari_multiscale_spatial_image/_version.py"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
